const fiszki = [
  // PRACA I KARIERA
  { id:'f1', es:'el currículum', pl:'CV / życiorys', cat:'Praca i kariera', emoji:'💼',
    ejemplo:'Envié mi currículum a diez empresas pero solo me llamaron dos.',
    ejemplo_pl:'Wysłałem CV do dziesięciu firm ale tylko dwie zadzwoniły.',
    tip:'💡 W Hiszpanii mówi się "currículum vitae" lub po prostu "currículum". Nie używaj "CV" w rozmowie.' },
  { id:'f2', es:'el sueldo', pl:'pensja / wynagrodzenie', cat:'Praca i kariera', emoji:'💼',
    ejemplo:'Mi sueldo no es muy alto pero el ambiente de trabajo es excelente.',
    ejemplo_pl:'Moja pensja nie jest zbyt wysoka ale atmosfera w pracy jest świetna.',
    tip:'💡 sueldo = pensja miesięczna. salario = wynagrodzenie (bardziej formalne). jornal = dniówka.' },
  { id:'f3', es:'el contrato', pl:'umowa', cat:'Praca i kariera', emoji:'💼',
    ejemplo:'Firmé un contrato de trabajo por un año con opción de renovación.',
    ejemplo_pl:'Podpisałem umowę o pracę na rok z opcją przedłużenia.',
    tip:'💡 firmar un contrato = podpisać umowę. contrato indefinido = umowa na czas nieokreślony.' },
  { id:'f4', es:'el ascenso', pl:'awans', cat:'Praca i kariera', emoji:'💼',
    ejemplo:'Después de tres años en la empresa, por fin conseguí un ascenso.',
    ejemplo_pl:'Po trzech latach w firmie w końcu dostałem awans.',
    tip:'💡 ascender = awansować (czasownik). Me han ascendido = awansowali mnie.' },
  { id:'f5', es:'despedir', pl:'zwolnić (z pracy)', cat:'Praca i kariera', emoji:'💼',
    ejemplo:'La empresa tuvo que despedir a veinte empleados por la crisis económica.',
    ejemplo_pl:'Firma musiała zwolnić dwudziestu pracowników przez kryzys ekonomiczny.',
    tip:'💡 despedir = zwolnić kogoś. dimitir / renunciar = zrezygnować samemu. No mylić z "despedirse" = pożegnać się!' },
  { id:'f6', es:'la reunión', pl:'zebranie / spotkanie', cat:'Praca i kariera', emoji:'💼',
    ejemplo:'Tenemos una reunión importante con los clientes a las diez de la mañana.',
    ejemplo_pl:'Mamy ważne spotkanie z klientami o dziesiątej rano.',
    tip:'💡 convocar una reunión = zwołać zebranie. cancelar una reunión = odwołać zebranie.' },
  { id:'f7', es:'el plazo', pl:'termin / deadline', cat:'Praca i kariera', emoji:'💼',
    ejemplo:'El plazo para entregar el proyecto es el viernes a mediodía.',
    ejemplo_pl:'Termin oddania projektu to piątek w południe.',
    tip:'💡 cumplir el plazo = dotrzymać terminu. fuera de plazo = po terminie. a tiempo = na czas.' },
  { id:'f8', es:'la baja', pl:'zwolnienie lekarskie', cat:'Praca i kariera', emoji:'💼',
    ejemplo:'Mi compañero lleva dos semanas de baja por una operación de rodilla.',
    ejemplo_pl:'Mój kolega jest od dwóch tygodni na zwolnieniu po operacji kolana.',
    tip:'💡 estar de baja = być na zwolnieniu. darse de baja = wziąć zwolnienie. baja por maternidad = urlop macierzyński.' },
  { id:'f9', es:'el jefe / la jefa', pl:'szef / szefowa', cat:'Praca i kariera', emoji:'💼',
    ejemplo:'Mi jefa es muy exigente pero también muy justa con todos los empleados.',
    ejemplo_pl:'Moja szefowa jest bardzo wymagająca ale też bardzo sprawiedliwa wobec wszystkich pracowników.',
    tip:'💡 jefe = szef bezpośredni. director/a = dyrektor. gerente = menedżer/prezes.' },
  { id:'f10', es:'solicitar', pl:'ubiegać się / składać wniosek', cat:'Praca i kariera', emoji:'💼',
    ejemplo:'Voy a solicitar una beca para estudiar en España el año que viene.',
    ejemplo_pl:'Zamierzam ubiegać się o stypendium na studia w Hiszpanii w przyszłym roku.',
    tip:'💡 solicitar un trabajo = ubiegać się o pracę. solicitar un préstamo = wnioskować o pożyczkę.' },

  // ZDROWIE I CIAŁO
  { id:'f11', es:'la herida', pl:'rana', cat:'Zdrowie i ciało', emoji:'🏥',
    ejemplo:'La herida no es grave pero necesitas limpiarla bien para evitar infecciones.',
    ejemplo_pl:'Rana nie jest poważna ale musisz ją dobrze oczyścić żeby uniknąć infekcji.',
    tip:'💡 herida = rana (ogólnie). corte = cięcie. golpe = siniak/stłuczenie. cicatriz = blizna.' },
  { id:'f12', es:'la receta', pl:'recepta / przepis', cat:'Zdrowie i ciało', emoji:'🏥',
    ejemplo:'El médico me dio una receta para los antibióticos y el jarabe para la tos.',
    ejemplo_pl:'Lekarz dał mi receptę na antybiotyki i syrop na kaszel.',
    tip:'💡 receta médica = recepta lekarska. receta de cocina = przepis kulinarny. Ten sam wyraz, różny kontekst!' },
  { id:'f13', es:'el análisis', pl:'badanie (krwi/moczu)', cat:'Zdrowie i ciało', emoji:'🏥',
    ejemplo:'El médico me mandó hacerme un análisis de sangre para comprobar el colesterol.',
    ejemplo_pl:'Lekarz zlecił mi zrobienie badania krwi żeby sprawdzić cholesterol.',
    tip:'💡 análisis de sangre = badanie krwi. hacerse un análisis = zrobić sobie badanie. Plural: los análisis (bez zmiany!).' },
  { id:'f14', es:'el quirófano', pl:'sala operacyjna', cat:'Zdrowie i ciało', emoji:'🏥',
    ejemplo:'La operación duró tres horas y el paciente pasó dos días en el quirófano.',
    ejemplo_pl:'Operacja trwała trzy godziny i pacjent spędził dwa dni na sali operacyjnej.',
    tip:'💡 operar = operować. operarse = być operowanym. Me van a operar la rodilla = będą mi operować kolano.' },
  { id:'f15', es:'la vacuna', pl:'szczepionka', cat:'Zdrowie i ciało', emoji:'🏥',
    ejemplo:'Es importante vacunarse contra la gripe cada año, especialmente los mayores.',
    ejemplo_pl:'Ważne jest szczepienie przeciw grypie każdego roku, szczególnie dla starszych.',
    tip:'💡 vacunarse = szczepić się. la vacunación = szczepienie. ponerse una vacuna = zaszczepić się.' },
  { id:'f16', es:'marearse', pl:'kręcić się w głowie / mdleć', cat:'Zdrowie i ciało', emoji:'🏥',
    ejemplo:'Me mareo mucho cuando viajo en barco — siempre tengo que tomar pastillas.',
    ejemplo_pl:'Bardzo mi się kręci w głowie kiedy podróżuję statkiem — zawsze muszę brać tabletki.',
    tip:'💡 el mareo = zawroty głowy / choroba lokomocyjna. estar mareado = mieć zawroty głowy.' },
  { id:'f17', es:'el embarazo', pl:'ciąża', cat:'Zdrowie i ciało', emoji:'🏥',
    ejemplo:'Durante el embarazo es muy importante seguir una dieta equilibrada y hacer ejercicio.',
    ejemplo_pl:'Podczas ciąży bardzo ważne jest przestrzeganie zbilansowanej diety i ćwiczenie.',
    tip:'💡 estar embarazada = być w ciąży. embarazada ≠ "embarrassed" (zawstydzony)! Fałszywy przyjaciel!' },
  { id:'f18', es:'la tensión', pl:'ciśnienie (krwi) / napięcie', cat:'Zdrowie i ciało', emoji:'🏥',
    ejemplo:'Mi abuelo tiene la tensión alta y tiene que tomar medicación todos los días.',
    ejemplo_pl:'Mój dziadek ma wysokie ciśnienie i musi brać leki każdego dnia.',
    tip:'💡 tensión alta/baja = wysokie/niskie ciśnienie. tomar la tensión = zmierzyć ciśnienie.' },
  { id:'f19', es:'el esguince', pl:'skręcenie (kostki)', cat:'Zdrowie i ciało', emoji:'🏥',
    ejemplo:'Me hice un esguince de tobillo jugando al fútbol y tuve que llevar vendaje.',
    ejemplo_pl:'Skręciłem kostkę grając w piłkę i musiałem nosić bandaż.',
    tip:'💡 hacerse un esguince = skręcić (staw). tobillo = kostka. muñeca = nadgarstek. rodilla = kolano.' },
  { id:'f20', es:'la alergia', pl:'alergia', cat:'Zdrowie i ciało', emoji:'🏥',
    ejemplo:'Tengo alergia al polen y en primavera lo paso muy mal con los ojos y la nariz.',
    ejemplo_pl:'Mam alergię na pyłki i wiosną bardzo cierpię z powodu oczu i nosa.',
    tip:'💡 ser alérgico a = być uczulonym na. tener alergia a = mieć alergię na. los antihistamínicos = leki antyhistaminowe.' },

  // PODRÓŻE I TRANSPORT
  { id:'f21', es:'el vuelo', pl:'lot', cat:'Podróże i transport', emoji:'✈️',
    ejemplo:'Nuestro vuelo sale a las seis de la mañana así que tenemos que ir al aeropuerto muy pronto.',
    ejemplo_pl:'Nasz lot odlatuje o szóstej rano więc musimy iść na lotnisko bardzo wcześnie.',
    tip:'💡 vuelo de ida = lot w jedną stronę. vuelo de ida y vuelta = lot w obie strony. escala = przesiadka.' },
  { id:'f22', es:'el retraso', pl:'opóźnienie', cat:'Podróże i transport', emoji:'✈️',
    ejemplo:'El vuelo llegó con dos horas de retraso debido a las malas condiciones meteorológicas.',
    ejemplo_pl:'Lot przybył z dwugodzinnym opóźnieniem z powodu złych warunków pogodowych.',
    tip:'💡 llegar con retraso = przybyć z opóźnieniem. llevar retraso = mieć opóźnienie. puntual = punktualny.' },
  { id:'f23', es:'el equipaje', pl:'bagaż', cat:'Podróże i transport', emoji:'✈️',
    ejemplo:'Facturé el equipaje en el aeropuerto y solo llevé una mochila pequeña de mano.',
    ejemplo_pl:'Nadałem bagaż na lotnisku i wziąłem tylko mały plecak podręczny.',
    tip:'💡 equipaje de mano = bagaż podręczny. facturar el equipaje = nadać bagaż. maleta = walizka.' },
  { id:'f24', es:'el alojamiento', pl:'zakwaterowanie', cat:'Podróże i transport', emoji:'✈️',
    ejemplo:'Buscamos alojamiento barato en el centro de la ciudad para tres noches.',
    ejemplo_pl:'Szukamy taniego zakwaterowania w centrum miasta na trzy noce.',
    tip:'💡 alojarse = zakwaterować się. alojamiento incluido = zakwaterowanie wliczone. hospedarse = zatrzymać się (w hotelu).' },
  { id:'f25', es:'el transbordo', pl:'przesiadka', cat:'Podróże i transport', emoji:'✈️',
    ejemplo:'Para ir a esa isla hay que hacer transbordo en el puerto de Valencia.',
    ejemplo_pl:'Żeby pojechać na tę wyspę trzeba zrobić przesiadkę w porcie Walencji.',
    tip:'💡 hacer transbordo = robić przesiadkę (pociąg/statek). hacer escala = robić przesiadkę (samolot).' },
  { id:'f26', es:'el atasco', pl:'korek uliczny', cat:'Podróże i transport', emoji:'✈️',
    ejemplo:'Llegué tarde a la reunión porque había un atasco enorme en la autopista.',
    ejemplo_pl:'Spóźniłem się na spotkanie bo był ogromny korek na autostradzie.',
    tip:'💡 estar atascado = stać w korku. hay mucho tráfico = jest duży ruch. embotellamiento = korek (synonim).' },
  { id:'f27', es:'la autopista', pl:'autostrada', cat:'Podróże i transport', emoji:'✈️',
    ejemplo:'En España muchas autopistas son de peaje — tienes que pagar para usarlas.',
    ejemplo_pl:'W Hiszpanii wiele autostrad jest płatnych — musisz zapłacić żeby z nich korzystać.',
    tip:'💡 autopista = autostrada (płatna). autovía = droga ekspresowa (bezpłatna). carretera = droga krajowa.' },
  { id:'f28', es:'el crucero', pl:'rejs / wycieczka statkiem', cat:'Podróże i transport', emoji:'✈️',
    ejemplo:'Mis padres hicieron un crucero por el Mediterráneo para celebrar su aniversario.',
    ejemplo_pl:'Moi rodzice zrobili rejs po Morzu Śródziemnym żeby uczcić rocznicę.',
    tip:'💡 hacer un crucero = odbyć rejs. barco de crucero = statek wycieczkowy. puerto = port.' },
  { id:'f29', es:'el seguro de viaje', pl:'ubezpieczenie podróżne', cat:'Podróże i transport', emoji:'✈️',
    ejemplo:'Siempre contrato un seguro de viaje antes de salir al extranjero por si acaso.',
    ejemplo_pl:'Zawsze wykupuję ubezpieczenie podróżne przed wyjazdem za granicę na wszelki wypadek.',
    tip:'💡 contratar un seguro = wykupić ubezpieczenie. por si acaso = na wszelki wypadek. cobertura = zakres ubezpieczenia.' },
  { id:'f30', es:'el horario', pl:'rozkład jazdy / harmonogram', cat:'Podróże i transport', emoji:'✈️',
    ejemplo:'Consulta el horario de trenes en la web antes de ir a la estación.',
    ejemplo_pl:'Sprawdź rozkład jazdy pociągów na stronie przed wyjściem na stację.',
    tip:'💡 horario de trenes/autobuses = rozkład jazdy. horario de trabajo = harmonogram pracy. horario de apertura = godziny otwarcia.' },

  // EMOCJE I RELACJE
  { id:'f31', es:'la confianza', pl:'zaufanie / pewność siebie', cat:'Emocje i relacje', emoji:'❤️',
    ejemplo:'La confianza es la base de cualquier relación — sin ella no funciona nada.',
    ejemplo_pl:'Zaufanie jest podstawą każdej relacji — bez niego nic nie działa.',
    tip:'💡 tener confianza en alguien = ufać komuś. tener confianza en uno mismo = mieć pewność siebie. de confianza = godny zaufania.' },
  { id:'f32', es:'la vergüenza', pl:'wstyd', cat:'Emocje i relacje', emoji:'❤️',
    ejemplo:'Me da mucha vergüenza hablar en público — me pongo rojo como un tomate.',
    ejemplo_pl:'Bardzo wstydzę się mówić publicznie — czerwienię się jak burak.',
    tip:'💡 dar vergüenza = wstydzić się (z dar). tener vergüenza = być zawstydzonym. qué vergüenza = co za wstyd!' },
  { id:'f33', es:'el orgullo', pl:'duma', cat:'Emocje i relacje', emoji:'❤️',
    ejemplo:'Sus padres sienten un orgullo enorme por todos sus logros académicos.',
    ejemplo_pl:'Jego rodzice czują ogromną dumę z jego osiągnięć akademickich.',
    tip:'💡 estar orgulloso de = być dumnym z. ¡Qué orgulloso estoy! = Jaki jestem dumny! orgullo puede ser negativo también (pycha).' },
  { id:'f34', es:'la soledad', pl:'samotność', cat:'Emocje i relacje', emoji:'❤️',
    ejemplo:'Vivir solo puede ser liberador pero a veces la soledad se hace muy difícil de soportar.',
    ejemplo_pl:'Życie samemu może być wyzwalające ale czasem samotność jest bardzo trudna do zniesienia.',
    tip:'💡 sentirse solo = czuć się samotnym. estar solo = być samemu (fizycznie). la soledad ≠ estar solo siempre.' },
  { id:'f35', es:'el apoyo', pl:'wsparcie / oparcie', cat:'Emocje i relacje', emoji:'❤️',
    ejemplo:'Durante los momentos difíciles, el apoyo de la familia es fundamental.',
    ejemplo_pl:'W trudnych momentach wsparcie rodziny jest fundamentalne.',
    tip:'💡 apoyar a alguien = wspierać kogoś. contar con el apoyo de = liczyć na wsparcie. apoyarse en = opierać się na.' },
  { id:'f36', es:'la pareja', pl:'para / partner / partnerka', cat:'Emocje i relacje', emoji:'❤️',
    ejemplo:'Mi pareja y yo llevamos cinco años juntos y el año que viene nos casamos.',
    ejemplo_pl:'Moja partnerka i ja jesteśmy razem od pięciu lat i w przyszłym roku bierzemy ślub.',
    tip:'💡 pareja = partner/partnerka (neutralne). novio/a = chłopak/dziewczyna. marido/mujer = mąż/żona.' },
  { id:'f37', es:'celos', pl:'zazdrość (w miłości)', cat:'Emocje i relacje', emoji:'❤️',
    ejemplo:'Los celos pueden destruir una relación si no se hablan con honestidad.',
    ejemplo_pl:'Zazdrość może zniszczyć związek jeśli nie mówi się o niej szczerze.',
    tip:'💡 tener celos = być zazdrosnym. dar celos = wzbudzać zazdrość. celoso/a = zazdrosny/a. Zawsze w liczbie mnogiej: los celos.' },
  { id:'f38', es:'la decepción', pl:'rozczarowanie', cat:'Emocje i relacje', emoji:'❤️',
    ejemplo:'Fue una gran decepción enterarse de que no había conseguido el trabajo.',
    ejemplo_pl:'Było wielkim rozczarowaniem dowiedzieć się że nie dostał tej pracy.',
    tip:'💡 estar decepcionado = być rozczarowanym. decepcionar a alguien = rozczarować kogoś. qué decepción = co za rozczarowanie!' },
  { id:'f39', es:'el malentendido', pl:'nieporozumienie', cat:'Emocje i relacje', emoji:'❤️',
    ejemplo:'La discusión fue solo un malentendido — los dos querían lo mismo pero no se explicaron bien.',
    ejemplo_pl:'Kłótnia była tylko nieporozumieniem — oboje chcieli tego samego ale nie wytłumaczyli się dobrze.',
    tip:'💡 haber un malentendido = być nieporozumieniu. aclarar un malentendido = wyjaśnić nieporozumienie.' },
  { id:'f40', es:'la ruptura', pl:'zerwanie / rozstanie', cat:'Emocje i relacje', emoji:'❤️',
    ejemplo:'Después de la ruptura, necesitó varios meses para recuperarse emocionalmente.',
    ejemplo_pl:'Po zerwaniu potrzebował kilku miesięcy żeby się emocjonalnie pozbierać.',
    tip:'💡 romper con alguien = zerwać z kimś. la ruptura = zerwanie/rozstanie. separarse = separować się (małżeństwo).' },

  // MIASTO I SPOŁECZEŃSTWO
  { id:'f41', es:'el ayuntamiento', pl:'urząd miejski / ratusz', cat:'Miasto i społeczeństwo', emoji:'🏙️',
    ejemplo:'Tienes que ir al ayuntamiento para registrarte como residente en esta ciudad.',
    ejemplo_pl:'Musisz pójść do urzędu miejskiego żeby zarejestrować się jako mieszkaniec tego miasta.',
    tip:'💡 ayuntamiento = urząd miejski. alcalde/alcaldesa = burmistrz/burmistrzyni. el consistorio = synonim ayuntamiento.' },
  { id:'f42', es:'el barrio', pl:'dzielnica', cat:'Miasto i społeczeństwo', emoji:'🏙️',
    ejemplo:'Vivo en un barrio tranquilo a las afueras de la ciudad — lejos del ruido del centro.',
    ejemplo_pl:'Mieszkam w spokojnej dzielnicy na obrzeżach miasta — daleko od hałasu centrum.',
    tip:'💡 barrio = dzielnica. vecindario = sąsiedztwo. los vecinos = sąsiedzi. el barrio antiguo = stare miasto.' },
  { id:'f43', es:'la manifestación', pl:'manifestacja / protest', cat:'Miasto i społeczeństwo', emoji:'🏙️',
    ejemplo:'Miles de personas participaron en la manifestación contra la subida de precios.',
    ejemplo_pl:'Tysiące ludzi uczestniczyło w manifestacji przeciw podwyżkom cen.',
    tip:'💡 manifestarse = manifestować się. convocar una manifestación = zorganizować manifestację. la huelga = strajk.' },
  { id:'f44', es:'la desigualdad', pl:'nierówność', cat:'Miasto i społeczeństwo', emoji:'🏙️',
    ejemplo:'La desigualdad social sigue siendo uno de los principales problemas de nuestra sociedad.',
    ejemplo_pl:'Nierówność społeczna nadal jest jednym z głównych problemów naszego społeczeństwa.',
    tip:'💡 la igualdad = równość. desigualdad social/económica = nierówność społeczna/ekonomiczna. el prefijo des- = negacja.' },
  { id:'f45', es:'el voluntariado', pl:'wolontariat', cat:'Miasto i społeczeństwo', emoji:'🏙️',
    ejemplo:'Hago voluntariado los fines de semana en una ONG que ayuda a personas sin hogar.',
    ejemplo_pl:'Robię wolontariat w weekendy w organizacji NGO która pomaga bezdomnym.',
    tip:'💡 hacer voluntariado = robić wolontariat. voluntario/a = wolontariusz/wolontariuszka. ONG = organizacja pozarządowa.' },
  { id:'f46', es:'el reciclaje', pl:'recykling', cat:'Miasto i społeczeństwo', emoji:'🏙️',
    ejemplo:'En mi ciudad el reciclaje es obligatorio — hay contenedores de diferentes colores.',
    ejemplo_pl:'W moim mieście recykling jest obowiązkowy — są pojemniki różnych kolorów.',
    tip:'💡 reciclar = recyclingować. el contenedor = pojemnik na śmieci. el medio ambiente = środowisko naturalne.' },
  { id:'f47', es:'la vivienda', pl:'mieszkanie / lokum', cat:'Miasto i społeczeństwo', emoji:'🏙️',
    ejemplo:'El precio de la vivienda en las grandes ciudades ha subido muchísimo en los últimos años.',
    ejemplo_pl:'Ceny mieszkań w dużych miastach bardzo wzrosły w ostatnich latach.',
    tip:'💡 vivienda = mieszkanie/lokum (ogólnie). piso = mieszkanie (w bloku). casa = dom. alquiler = wynajem.' },
  { id:'f48', es:'la seguridad ciudadana', pl:'bezpieczeństwo publiczne', cat:'Miasto i społeczeństwo', emoji:'🏙️',
    ejemplo:'La seguridad ciudadana ha mejorado mucho desde que pusieron más cámaras en el barrio.',
    ejemplo_pl:'Bezpieczeństwo publiczne bardzo się poprawiło odkąd zainstalowano więcej kamer w dzielnicy.',
    tip:'💡 seguro/a = bezpieczny/a. sentirse seguro = czuć się bezpiecznie. la policía = policja. el delito = przestępstwo.' },
  { id:'f49', es:'la contaminación', pl:'zanieczyszczenie', cat:'Miasto i społeczeństwo', emoji:'🏙️',
    ejemplo:'La contaminación del aire en las ciudades grandes es un grave problema de salud pública.',
    ejemplo_pl:'Zanieczyszczenie powietrza w dużych miastach jest poważnym problemem zdrowia publicznego.',
    tip:'💡 contaminar = zanieczyszczać. contaminación atmosférica = zanieczyszczenie powietrza. las emisiones = emisje.' },
  { id:'f50', es:'la infraestructura', pl:'infrastruktura', cat:'Miasto i społeczeństwo', emoji:'🏙️',
    ejemplo:'El gobierno ha invertido millones en mejorar la infraestructura de transporte público.',
    ejemplo_pl:'Rząd zainwestował miliony w poprawę infrastruktury transportu publicznego.',
    tip:'💡 infraestructura viaria = infrastruktura drogowa. invertir en = inwestować w. mejorar = poprawiać.' },

  // JEDZENIE I GOTOWANIE
  { id:'f51', es:'el ingrediente', pl:'składnik', cat:'Jedzenie i gotowanie', emoji:'🍳',
    ejemplo:'Para hacer esta receta necesitas ingredientes frescos y de buena calidad.',
    ejemplo_pl:'Żeby zrobić ten przepis potrzebujesz świeżych składników dobrej jakości.',
    tip:'💡 los ingredientes = składniki (zawsze pl w przepisach). añadir un ingrediente = dodać składnik.' },
  { id:'f52', es:'la nevera', pl:'lodówka', cat:'Jedzenie i gotowanie', emoji:'🍳',
    ejemplo:'Guarda las sobras en la nevera y cómetelas antes de que caduquen.',
    ejemplo_pl:'Włóż resztki do lodówki i zjedz je zanim się przeterminują.',
    tip:'💡 nevera = lodówka (Hiszpania). frigorífico = synonim (bardziej formalny). congelador = zamrażarka.' },
  { id:'f53', es:'la receta', pl:'przepis', cat:'Jedzenie i gotowanie', emoji:'🍳',
    ejemplo:'Mi abuela tiene recetas tradicionales que ha guardado durante décadas.',
    ejemplo_pl:'Moja babcia ma tradycyjne przepisy które przechowuje od dziesięcioleci.',
    tip:'💡 receta de cocina = przepis kulinarny. receta médica = recepta lekarska. Uwaga — dwa znaczenia!' },
  { id:'f54', es:'el sabor', pl:'smak', cat:'Jedzenie i gotowanie', emoji:'🍳',
    ejemplo:'Este plato tiene un sabor increíble — un poco dulce y un poco picante a la vez.',
    ejemplo_pl:'To danie ma niesamowity smak — trochę słodki i trochę ostry jednocześnie.',
    tip:'💡 saber a = smakować jak. sabe a limón = smakuje jak cytryna. sabor dulce/salado/amargo/picante = słodki/słony/gorzki/ostry.' },
  { id:'f55', es:'freír', pl:'smażyć', cat:'Jedzenie i gotowanie', emoji:'🍳',
    ejemplo:'En España es muy común freír los alimentos en aceite de oliva.',
    ejemplo_pl:'W Hiszpanii bardzo powszechne jest smażenie potraw na oliwie z oliwek.',
    tip:'💡 freír → frito (participio nieregularne!). freír a fuego lento = smażyć na wolnym ogniu. la sartén = patelnia.' },
  { id:'f56', es:'el caldo', pl:'bulion / wywar', cat:'Jedzenie i gotowanie', emoji:'🍳',
    ejemplo:'Preparé un caldo de pollo casero para cuando alguien se pone enfermo en casa.',
    ejemplo_pl:'Przygotowałem domowy bulion z kurczaka na wypadek gdy ktoś w domu zachoruje.',
    tip:'💡 caldo de pollo/verduras/carne = bulion z kurczaka/warzyw/mięsa. la sopa = zupa (z caldo jako baza).' },
  { id:'f57', es:'la masa', pl:'ciasto (surowe) / masa', cat:'Jedzenie i gotowanie', emoji:'🍳',
    ejemplo:'Hay que amasar la masa durante diez minutos hasta que quede elástica y suave.',
    ejemplo_pl:'Trzeba wyrabiać ciasto przez dziesięć minut aż stanie się elastyczne i gładkie.',
    tip:'💡 masa de pan = ciasto chlebowe. masa quebrada = kruche ciasto. amasar = wyrabiać ciasto.' },
  { id:'f58', es:'el aliño', pl:'sos do sałatki / przyprawa', cat:'Jedzenie i gotowanie', emoji:'🍳',
    ejemplo:'El aliño típico español es aceite de oliva, vinagre y sal — muy sencillo pero delicioso.',
    ejemplo_pl:'Typowy hiszpański dressing to oliwa z oliwek, ocet i sól — bardzo prosty ale pyszny.',
    tip:'💡 aliñar = przyprawiać/zaprawiać. el aderezo = synonim. condimentar = przyprawiać (ogólnie).' },
  { id:'f59', es:'caducar', pl:'przeterminować się', cat:'Jedzenie i gotowanie', emoji:'🍳',
    ejemplo:'Esta leche caduca mañana — mejor usarla hoy para no desperdiciarla.',
    ejemplo_pl:'To mleko przeterminuje się jutro — lepiej użyć go dziś żeby nie marnować.',
    tip:'💡 fecha de caducidad = data ważności. caducado = przeterminowany. desperdiciar = marnować.' },
  { id:'f60', es:'el trozo', pl:'kawałek / fragment', cat:'Jedzenie i gotowanie', emoji:'🍳',
    ejemplo:'¿Me puedes dar un trozo de tarta? Solo uno pequeño, que estoy a dieta.',
    ejemplo_pl:'Czy możesz mi dać kawałek ciasta? Tylko mały, bo jestem na diecie.',
    tip:'💡 un trozo de = kawałek czegoś. cortar en trozos = pokroić na kawałki. la ración = porcja (w restauracji).' },

  // DOM I MIESZKANIE
  { id:'f61', es:'el alquiler', pl:'czynsz / wynajem', cat:'Dom i mieszkanie', emoji:'🏠',
    ejemplo:'El alquiler en Madrid ha subido tanto que muchos jóvenes no pueden permitírselo.',
    ejemplo_pl:'Czynsz w Madrycie wzrósł tak bardzo że wielu młodych nie może sobie na niego pozwolić.',
    tip:'💡 pagar el alquiler = płacić czynsz. alquilar un piso = wynajmować mieszkanie. el arrendamiento = najem (formalny).' },
  { id:'f62', es:'el propietario', pl:'właściciel', cat:'Dom i mieszkanie', emoji:'🏠',
    ejemplo:'El propietario del piso no quiere hacer las reparaciones necesarias en el baño.',
    ejemplo_pl:'Właściciel mieszkania nie chce zrobić niezbędnych napraw w łazience.',
    tip:'💡 propietario/a = właściciel/ka. el inquilino/a = najemca/lokator. el casero/a = gospodarz/gospodyni (potoczne).' },
  { id:'f63', es:'la mudanza', pl:'przeprowadzka', cat:'Dom i mieszkanie', emoji:'🏠',
    ejemplo:'La mudanza fue agotadora — tardamos dos días enteros en mover todos los muebles.',
    ejemplo_pl:'Przeprowadzka była wyczerpująca — zajęło nam dwa całe dni żeby przenieść wszystkie meble.',
    tip:'💡 mudarse = przeprowadzać się. hacer la mudanza = robić przeprowadzkę. la empresa de mudanzas = firma przeprowadzkowa.' },
  { id:'f64', es:'la fontanería', pl:'hydraulika / instalacja wodno-kanalizacyjna', cat:'Dom i mieszkanie', emoji:'🏠',
    ejemplo:'Hay una avería en la fontanería — el agua del baño no para de gotear.',
    ejemplo_pl:'Jest awaria w hydraulice — woda w łazience cały czas kapie.',
    tip:'💡 el fontanero/a = hydraulik. la avería = awaria. gotear = kapać. la tubería = rura.' },
  { id:'f65', es:'el tejado', pl:'dach', cat:'Dom i mieszkanie', emoji:'🏠',
    ejemplo:'Después de la tormenta el tejado empezó a tener goteras y hubo que repararlo.',
    ejemplo_pl:'Po burzy dach zaczął przeciekać i trzeba go było naprawić.',
    tip:'💡 tejado = dach spadzisty (kafelki). azotea = taras dachowy (płaski). el techo = sufit (wewnątrz). gotera = przeciek.' },
  { id:'f66', es:'la calefacción', pl:'ogrzewanie', cat:'Dom i mieszkanie', emoji:'🏠',
    ejemplo:'En invierno la calefacción es imprescindible — sin ella el piso se queda helado.',
    ejemplo_pl:'Zimą ogrzewanie jest niezbędne — bez niego mieszkanie jest lodowate.',
    tip:'💡 encender/apagar la calefacción = włączyć/wyłączyć ogrzewanie. calefacción central = ogrzewanie centralne.' },
  { id:'f67', es:'el electrodoméstico', pl:'sprzęt AGD', cat:'Dom i mieszkanie', emoji:'🏠',
    ejemplo:'Al mudarse compraron todos los electrodomésticos nuevos: lavadora, lavavajillas y microondas.',
    ejemplo_pl:'Przy przeprowadzce kupili wszystkie nowe sprzęty AGD: pralkę, zmywarkę i mikrofalę.',
    tip:'💡 electrodomésticos de línea blanca = duże AGD (pralka, lodówka). la lavadora = pralka. el lavavajillas = zmywarka.' },
  { id:'f68', es:'el vecino', pl:'sąsiad', cat:'Dom i mieszkanie', emoji:'🏠',
    ejemplo:'Mi vecino de arriba hace mucho ruido por las noches y no me deja dormir.',
    ejemplo_pl:'Mój sąsiad z góry robi dużo hałasu w nocy i nie pozwala mi spać.',
    tip:'💡 vecino de arriba/abajo = sąsiad z góry/dołu. vecino de al lado = sąsiad obok. la comunidad de vecinos = wspólnota mieszkaniowa.' },
  { id:'f69', es:'las obras', pl:'remont / roboty budowlane', cat:'Dom i mieszkanie', emoji:'🏠',
    ejemplo:'Llevamos tres meses con obras en casa — estamos reformando la cocina y el baño.',
    ejemplo_pl:'Od trzech miesięcy robimy remont w domu — przebudowujemy kuchnię i łazienkę.',
    tip:'💡 hacer obras = robić remont. estar en obras = być w remoncie. el obrero = robotnik budowlany.' },
  { id:'f70', es:'el presupuesto', pl:'budżet / kosztorys', cat:'Dom i mieszkanie', emoji:'🏠',
    ejemplo:'Pedimos presupuesto a tres empresas antes de decidir quién haría las obras.',
    ejemplo_pl:'Poprosiliśmy o kosztorys trzy firmy zanim zdecydowaliśmy kto zrobi remont.',
    tip:'💡 presupuesto = budżet (finansowy) lub kosztorys (od wykonawcy). ajustarse al presupuesto = trzymać się budżetu.' },

  // NAUKA I EDUKACJA
  { id:'f71', es:'el aprendizaje', pl:'nauka / uczenie się', cat:'Nauka i edukacja', emoji:'📚',
    ejemplo:'El aprendizaje de idiomas requiere constancia y práctica diaria.',
    ejemplo_pl:'Nauka języków wymaga wytrwałości i codziennej praktyki.',
    tip:'💡 aprendizaje = proces uczenia się. aprender = uczyć się. el/la aprendiz = uczeń/praktykant.' },
  { id:'f72', es:'la beca', pl:'stypendium', cat:'Nauka i edukacja', emoji:'📚',
    ejemplo:'Consiguió una beca para estudiar un máster en la Universidad de Barcelona.',
    ejemplo_pl:'Dostał stypendium na studia magisterskie na Uniwersytecie Barcelońskim.',
    tip:'💡 solicitar una beca = ubiegać się o stypendium. beca de investigación = stypendium badawcze. becario/a = stypendysta/ka.' },
  { id:'f73', es:'el suspenso', pl:'ocena niedostateczna / oblanie', cat:'Nauka i edukacja', emoji:'📚',
    ejemplo:'Saqué un suspenso en matemáticas y tendré que repetir el examen en septiembre.',
    ejemplo_pl:'Dostałem niedostateczny z matematyki i będę musiał powtórzyć egzamin we wrześniu.',
    tip:'💡 suspender = oblać (egzamin). aprobar = zdać. sacar un suspenso/aprobado = dostać ndst/dst. el notable = dobry (7-8). el sobresaliente = bardzo dobry (9-10).' },
  { id:'f74', es:'el plagio', pl:'plagiat', cat:'Nauka i edukacja', emoji:'📚',
    ejemplo:'En la universidad el plagio está penalizado con la expulsión del curso.',
    ejemplo_pl:'Na uniwersytecie plagiat jest karany wyrzuceniem z kursu.',
    tip:'💡 plagiar = plagiatować. el plagiador/a = plagiator/ka. citar las fuentes = cytować źródła.' },
  { id:'f75', es:'el horario lectivo', pl:'plan lekcji / rozkład zajęć', cat:'Nauka i edukacja', emoji:'📚',
    ejemplo:'El horario lectivo del instituto empieza a las ocho y termina a las tres.',
    ejemplo_pl:'Plan lekcji w liceum zaczyna się o ósmej i kończy o trzeciej.',
    tip:'💡 lectivo = związany z nauczaniem. día lectivo = dzień nauki. hora lectiva = godzina lekcyjna.' },
  { id:'f76', es:'el título', pl:'tytuł / dyplom', cat:'Nauka i edukacja', emoji:'📚',
    ejemplo:'Para ese trabajo piden un título universitario y dos años de experiencia.',
    ejemplo_pl:'Na to stanowisko wymagają dyplomu uniwersyteckiego i dwóch lat doświadczenia.',
    tip:'💡 título universitario = dyplom uczelni. título de grado = licencjat. título de máster = magisterium. titularse = ukończyć studia.' },
  { id:'f77', es:'el temario', pl:'program / materiał do nauki', cat:'Nauka i edukacja', emoji:'📚',
    ejemplo:'El temario del examen incluye todos los temas del segundo trimestre.',
    ejemplo_pl:'Program egzaminu obejmuje wszystkie tematy z drugiego trymestru.',
    tip:'💡 temario = zakres materiału na egzamin. el programa = program kursu/przedmiotu. el índice = spis treści.' },
  { id:'f78', es:'el fracaso escolar', pl:'niepowodzenia szkolne / wypadanie z systemu', cat:'Nauka i edukacja', emoji:'📚',
    ejemplo:'El fracaso escolar es un problema social que afecta a muchos jóvenes en situación vulnerable.',
    ejemplo_pl:'Niepowodzenia szkolne są problemem społecznym który dotyka wielu młodych w trudnej sytuacji.',
    tip:'💡 fracasar = ponosić porażkę. el fracaso = porażka. fracaso escolar = zjawisko porzucania szkoły przez uczniów.' },
  { id:'f79', es:'la matrícula', pl:'wpisowe / rejestracja na kurs', cat:'Nauka i edukacja', emoji:'📚',
    ejemplo:'La matrícula de la universidad pública es mucho más barata que la privada.',
    ejemplo_pl:'Wpisowe na uczelni publicznej jest dużo tańsze niż na prywatnej.',
    tip:'💡 matricularse = zapisać się (na kurs/uczelnię). la matrícula del coche = tablice rejestracyjne. Dwa znaczenia!' },
  { id:'f80', es:'el nivel', pl:'poziom', cat:'Nauka i edukacja', emoji:'📚',
    ejemplo:'Mi nivel de español ha mejorado mucho desde que empecé a practicar todos los días.',
    ejemplo_pl:'Mój poziom hiszpańskiego bardzo się poprawił odkąd zacząłem ćwiczyć codziennie.',
    tip:'💡 nivel básico/intermedio/avanzado = poziom podstawowy/średni/zaawansowany. estar al mismo nivel = być na tym samym poziomie.' },

  // TECHNOLOGIA I MEDIA
  { id:'f81', es:'la contraseña', pl:'hasło', cat:'Technologia i media', emoji:'💻',
    ejemplo:'Usa una contraseña segura con letras, números y símbolos para proteger tu cuenta.',
    ejemplo_pl:'Używaj bezpiecznego hasła z literami, cyframi i symbolami żeby chronić swoje konto.',
    tip:'💡 cambiar la contraseña = zmienić hasło. olvidar la contraseña = zapomnieć hasła. la clave = synonim (hasło/kod).' },
  { id:'f82', es:'la pantalla', pl:'ekran', cat:'Tecnologia i media', emoji:'💻',
    ejemplo:'Pasamos demasiadas horas mirando pantallas — el móvil, el ordenador, la televisión.',
    ejemplo_pl:'Spędzamy zbyt wiele godzin patrząc w ekrany — telefon, komputer, telewizor.',
    tip:'💡 pantalla táctil = ekran dotykowy. pantalla completa = pełny ekran. compartir pantalla = udostępnić ekran.' },
  { id:'f83', es:'la red social', pl:'sieć społecznościowa', cat:'Tecnologia i media', emoji:'💻',
    ejemplo:'Las redes sociales pueden ser útiles pero también adictivas si no se usan con moderación.',
    ejemplo_pl:'Sieci społecznościowe mogą być przydatne ale też uzależniające jeśli nie używa się ich z umiarem.',
    tip:'💡 las redes sociales = media społecznościowe. publicar en redes = publikować w mediach. el seguidor = obserwujący.' },
  { id:'f84', es:'la aplicación', pl:'aplikacja', cat:'Tecnologia i media', emoji:'💻',
    ejemplo:'Descargué una aplicación para aprender vocabulario y la uso cada día en el metro.',
    ejemplo_pl:'Pobrałem aplikację do nauki słownictwa i używam jej każdego dnia w metrze.',
    tip:'💡 aplicación = aplikacja (formalne). la app = app (potoczne). descargar/instalar una app = pobrać/zainstalować aplikację.' },
  { id:'f85', es:'el archivo', pl:'plik / archiwum', cat:'Tecnologia i media', emoji:'💻',
    ejemplo:'No puedo abrir el archivo que me enviaste — creo que está en un formato incompatible.',
    ejemplo_pl:'Nie mogę otworzyć pliku który mi wysłałeś — chyba jest w niekompatybilnym formacie.',
    tip:'💡 archivo = plik (ordenador) lub archiwum (dokumenty). guardar un archivo = zapisać plik. adjuntar = załączyć.' },
  { id:'f86', es:'la nube', pl:'chmura (internet)', cat:'Tecnologia i media', emoji:'💻',
    ejemplo:'Guardo todas mis fotos en la nube para no perderlas si se me rompe el móvil.',
    ejemplo_pl:'Przechowuję wszystkie zdjęcia w chmurze żeby ich nie stracić gdy telefon mi się zepsuje.',
    tip:'💡 la nube = chmura (internet). almacenamiento en la nube = przechowywanie w chmurze. la nube también = chmura (pogoda).' },
  { id:'f87', es:'la inteligencia artificial', pl:'sztuczna inteligencia', cat:'Tecnologia i media', emoji:'💻',
    ejemplo:'La inteligencia artificial está transformando muchos sectores, desde la medicina hasta el arte.',
    ejemplo_pl:'Sztuczna inteligencja transformuje wiele sektorów, od medycyny po sztukę.',
    tip:'💡 la IA = AI (skrót). el algoritmo = algorytm. los datos = dane. la automatización = automatyzacja.' },
  { id:'f88', es:'la señal', pl:'sygnał', cat:'Tecnologia i media', emoji:'💻',
    ejemplo:'Aquí no hay señal — voy a salir un momento para poder hacer la llamada.',
    ejemplo_pl:'Tu nie ma sygnału — wyjdę na chwilę żeby móc zadzwonić.',
    tip:'💡 sin señal = bez zasięgu. señal wifi = sygnał WiFi. tener buena/mala señal = mieć dobry/zły zasięg.' },
  { id:'f89', es:'la actualización', pl:'aktualizacja', cat:'Tecnologia i media', emoji:'💻',
    ejemplo:'El móvil me pide que instale una actualización del sistema pero no tengo batería.',
    ejemplo_pl:'Telefon prosi mnie żebym zainstalował aktualizację systemu ale nie mam baterii.',
    tip:'💡 actualizar = aktualizować. la última versión = najnowsza wersja. desactualizado = nieaktualny/przestarzały.' },
  { id:'f90', es:'el titular', pl:'nagłówek / tytuł (artykułu)', cat:'Tecnologia i media', emoji:'💻',
    ejemplo:'El titular de la noticia era tan llamativo que todo el mundo lo compartió en redes.',
    ejemplo_pl:'Nagłówek wiadomości był tak przykuwający uwagę że wszyscy udostępnili go w mediach.',
    tip:'💡 el titular = nagłówek (gazety/artykułu). los titulares = nagłówki/skrót wiadomości. llamativo = przykuwający uwagę.' },

  // NATURA I ŚRODOWISKO
  { id:'f91', es:'el bosque', pl:'las', cat:'Natura i środowisko', emoji:'🌿',
    ejemplo:'Pasamos el fin de semana haciendo senderismo por el bosque — el aire era increíble.',
    ejemplo_pl:'Spędziliśmy weekend na wędrówkach po lesie — powietrze było niesamowite.',
    tip:'💡 bosque = las (duży). el bosquecillo = lasek (mały). la selva = dżungla. el pinar = las sosnowy.' },
  { id:'f92', es:'la sequía', pl:'susza', cat:'Natura i środowisko', emoji:'🌿',
    ejemplo:'La sequía de este verano ha sido la peor en décadas — los embalses están casi vacíos.',
    ejemplo_pl:'Susza tego lata była najgorsza od dziesięcioleci — zbiorniki są prawie puste.',
    tip:'💡 la sequía = susza. seco/a = suchy/a. el embalse = zbiornik wodny. la escasez de agua = niedobór wody.' },
  { id:'f93', es:'la inundación', pl:'powódź', cat:'Natura i środowisko', emoji:'🌿',
    ejemplo:'Las inundaciones causadas por las lluvias torrenciales dejaron muchas familias sin hogar.',
    ejemplo_pl:'Powodzie spowodowane przez ulewne deszcze pozbawiły wiele rodzin domów.',
    tip:'💡 inundarse = zalewać się. las lluvias torrenciales = ulewne deszcze. el desbordamiento = wylanie (rzeki).' },
  { id:'f94', es:'el reciclaje', pl:'recykling', cat:'Natura i środowisko', emoji:'🌿',
    ejemplo:'El reciclaje correcto es fundamental para reducir la cantidad de residuos que van al vertedero.',
    ejemplo_pl:'Prawidłowy recykling jest fundamentalny żeby zmniejszyć ilość odpadów trafiających na wysypisko.',
    tip:'💡 reciclar = recyclingować. los residuos = odpady. el vertedero = wysypisko. el contenedor azul/verde/amarillo = niebieski/zielony/żółty pojemnik.' },
  { id:'f95', es:'el calentamiento global', pl:'globalne ocieplenie', cat:'Natura i środowisko', emoji:'🌿',
    ejemplo:'El calentamiento global es una amenaza real que requiere acción urgente de todos los países.',
    ejemplo_pl:'Globalne ocieplenie jest prawdziwym zagrożeniem które wymaga pilnych działań wszystkich krajów.',
    tip:'💡 el cambio climático = zmiana klimatu. las emisiones de CO₂ = emisje CO₂. la huella de carbono = ślad węglowy.' },
  { id:'f96', es:'la especie', pl:'gatunek', cat:'Natura i środowisko', emoji:'🌿',
    ejemplo:'Cada año desaparecen miles de especies animales y vegetales a causa de la deforestación.',
    ejemplo_pl:'Co roku znikają tysiące gatunków zwierząt i roślin z powodu wylesiania.',
    tip:'💡 especie en peligro de extinción = gatunek zagrożony wymarciem. la biodiversidad = bioróżnorodność.' },
  { id:'f97', es:'el vertido', pl:'wylew / zrzut (substancji)', cat:'Natura i środowisko', emoji:'🌿',
    ejemplo:'El vertido de productos químicos al río contaminó el agua durante varios meses.',
    ejemplo_pl:'Wylew substancji chemicznych do rzeki skażał wodę przez kilka miesięcy.',
    tip:'💡 verter = wylewać/zrzucać. vertido de petróleo = wyciek ropy. el derrame = wyciek (synonim).' },
  { id:'f98', es:'renovable', pl:'odnawialny', cat:'Natura i środowisko', emoji:'🌿',
    ejemplo:'España está apostando por las energías renovables como la solar y la eólica.',
    ejemplo_pl:'Hiszpania stawia na energie odnawialne takie jak słoneczna i wiatrowa.',
    tip:'💡 energía renovable = energia odnawialna. energía solar/eólica = energia słoneczna/wiatrowa. no renovable = nieodnawialna.' },
  { id:'f99', es:'la deforestación', pl:'wylesianie', cat:'Natura i środowisko', emoji:'🌿',
    ejemplo:'La deforestación de la Amazonia es uno de los mayores problemas medioambientales del mundo.',
    ejemplo_pl:'Wylesianie Amazonii jest jednym z największych problemów środowiskowych na świecie.',
    tip:'💡 deforestar = wylesić. el bosque tropical = las tropikalny. la reforestación = zalesianie (odwrotność).' },
  { id:'f100', es:'el ecosistema', pl:'ekosystem', cat:'Natura i środowisko', emoji:'🌿',
    ejemplo:'La contaminación del mar destruye el ecosistema marino y amenaza miles de especies.',
    ejemplo_pl:'Zanieczyszczenie morza niszczy ekosystem morski i zagraża tysiącom gatunków.',
    tip:'💡 ecosistema marino/terrestre = ekosystem morski/lądowy. el hábitat = siedlisko. la cadena alimentaria = łańcuch pokarmowy.' },
];

const fiszki_cats = ['Praca i kariera', 'Zdrowie i ciało', 'Podróże i transport', 'Emocje i relacje', 'Miasto i społeczeństwo', 'Jedzenie i gotowanie', 'Dom i mieszkanie', 'Nauka i edukacja', 'Technologia i media', 'Natura i środowisko'
];